on:
  schedule:
    - cron: "0 0 * * *" #Everyday at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python3 ./updatepuzzle.py
   
   
        
       

